Версия 1.2
PAZderev/java-kanban pull request #1
Opened 2024-04-04 17:57 UTC by PAZderev

Добавлены классы TaskLinkedList, TaskNode
Обновить реализацию истории задач через связанный список
Написать новые тесты

2024-04-04 20:00 UTC, PAZderev commented
Тесты на Github просто висят в процессе, поэтому отправил на ревью в таком состоянии

2024-04-05 13:28 UTC, db-exp requested changes

2024-04-05 13:28 UTC, db-exp commented on src/managers/classes/InMemoryTaskManager.java
> +        inMemoryHistoryManager.remove(id);
inMemoryHistoryManager я бы переименовал в  historyManager - TaskManager'у не обязательно знать детали реализации

2024-04-05 18:41 UTC, PAZderev commented
Почему-то я делаю amend коммита в Idea и она все равно создает новые коммиты :(

2024-04-06 12:18 UTC, db-exp requested changes

2024-04-06 12:18 UTC, db-exp commented on src/managers/classes/InMemoryHistoryManager.java
> +    public TaskLinkedList getHistory() {
Реализация метода getHistory должна перекладывать задачи из связного списка в ArrayList для формирования ответа.

2024-04-06 12:18 UTC, db-exp commented on src/managers/classes/Managers.java
>      public InMemoryTaskManager getDefault() {
тут вместо InMemoryTaskManager должен быть тип TaskManager

2024-04-06 12:18 UTC, db-exp commented on src/managers/classes/Managers.java
>      private InMemoryTaskManager inMemoryTaskManager;
тут вместо InMemoryTaskManager должен быть тип TaskManager

2024-04-06 12:18 UTC, db-exp commented on src/managers/classes/Managers.java
вместо 
 public static HistoryManager getDefaultHistory() {
        return new InMemoryHistoryManager();
    }

лучше также как в getDefault()  TaskManager'а проверять на null и либо создавать, либо отдавать существующий

2024-04-06 12:18 UTC, db-exp commented on src/managers/interfaces/HistoryManager.java
> +    TaskLinkedList getHistory();
лучше вернуть как было

2024-04-06 12:18 UTC, db-exp commented on src/utils/TaskLinkedList.java
> +    public TaskNode add(Task task) {
вот тут не проверяется просматривали еще раз или нет

Если какая-либо задача просматривалась несколько раз, в истории должен отобразиться только последний просмотр. Предыдущий просмотр должен быть удалён сразу после появления нового — за O(1)

2024-04-06 12:18 UTC, db-exp commented on src/utils/TaskLinkedList.java
> +public class TaskLinkedList {
не хватает индекса

"Поэтому вам предстоит написать собственную реализацию связного списка с индексом по id задачи."

2024-04-06 15:41 UTC, PAZderev commented
Снова попытался с --amend закоммитить, но не получилось, все равно GitHub создает дополнительный коммит, погуглил с чем это связано - он так защищает от потери данных, если ведется разработка несколькими людьми. Тогда в будущем откажусь от коммитов с --amend и буду коммитить по обычному, чтобы не плодить коммиты так, как выше.

2024-04-07 23:13 UTC, db-exp approved these changes

2024-04-08 14:09 UTC, merged