Версия 1.4
PAZderev/java-kanban pull request #3
Opened 2024-05-05 13:14 UTC by PAZderev

Добавить поля creationTime, duration у задач.
Добавить метод clearHistory у интерфейса HistoryManager (для корректной работы тестов)
Преобразовать логику с введённым функционалом
Добавить тесты для реализованного функционала.

2024-05-05 14:24 UTC, db-exp requested changes

2024-05-05 14:24 UTC, db-exp commented on src/managers/classes/FileBackedTaskManager.java
> +                if (params.length < 7) { // Необходимо минимум 7 элементов для правильной десериализации
7 можно в константу для того, чтобы уйти от "магических числе"

2024-05-05 14:24 UTC, db-exp commented on src/managers/classes/FileBackedTaskManager.java
не забываем модификаторы у методов

2024-05-05 14:24 UTC, db-exp commented on src/managers/classes/InMemoryTaskManager.java
> +    private boolean updatePriority(Task task) {
"можно лучше" неинформативное имя - лучше назвать checkTime и манипуляции со списком  prioritizedTasks делать в отдельном методе

2024-05-05 14:24 UTC, db-exp commented on test/managers/classes/TaskManagerTest.java
> +        assertEquals(task2, taskManager.getTaskById(task2.getId()));
а разве должна создаться вторая задача? у нее тот же интервал

2024-05-05 14:24 UTC, db-exp commented on src/tasks/Epic.java
> +    private void updateTiming(SubTask subTask, String sign) {
тоже можно было бы разбить на два метода для удаления и добавления, чтобы не делать + и -

2024-05-05 14:24 UTC, db-exp commented on src/tasks/SubTask.java
> +        LocalDateTime time = params[6].equals("null") ? null : LocalDateTime.parse(params[6]);
можно лучше - индексы в идеале тоже превращаются в статические переменные, чтобы было не param[6], а param[TASK_TIME]

2024-05-07 13:41 UTC, PAZderev commented on test/managers/classes/TaskManagerTest.java
> +        assertEquals(task2, taskManager.getTaskById(task2.getId()));
да, пояснил в пачке

2024-05-07 13:48 UTC, PAZderev commented on src/tasks/Epic.java
> +    private void updateTiming(SubTask subTask, String sign) {
Метод updateTiming разбил на два. Метод updateCounterAndStatus считаю нецелесообразно обновлять, т.к. будут абсолютно два одинаковых метода, различающиеся лишь значением константы diff. В них вызывались бы одни и теже методы

2024-05-07 13:55 UTC, PAZderev commented
Оставил сообщение в пачке по поводу одного коммента + свой вопрос

2024-05-07 15:34 UTC, db-exp approved these changes

2024-05-07 20:00 UTC, merged